#!/bin/sh
#
# Mirror fb0 -> fb1 using fbcp
#

case "$1" in
  start)
	printf "Starting frame buffer mirror: "
	umask 077

	start-stop-daemon -S -q -m -p /var/run/fbcp.pid --exec /usr/sbin/fbcp &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping frame buffer mirror: "
	start-stop-daemon -K -q -p /var/run/fbcp.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
