#!/bin/sh
#
# Mirror fb0 and fb1
#

case "$1" in
  start)
        printf "Mirroring frame buffers: "

        start-stop-daemon -S -q -m -p /var/run/fbcp.pid  --exec /usr/sbin/fbcp &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stop mirroring frame buffers: "
        start-stop-daemon -K -q -p /var/run/fbcp.pid
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

